# Site settings
# For test repository "academic-homepage-test":
baseurl: "/academic-homepage-test"

# When moving to official user site "Wendy-xxxxx.github.io", change to:
# baseurl: ""

markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Asia/Shanghai

collections:
  - publications
  - news
  - showcase
  - posts
